/* Generated by tools/sinconv.py -- do not edit.
 *
 * The VDI's sine table from EmuTOS (vdi/vdi_gdp.c),
 * Copyright 1982 by Digital Research Inc., Copyright 1999 by Caldera,
 * Inc., Copyright 2002-2022 The EmuTOS development team, GPL v2 or
 * later.  Sines of 0 to 89.6 degrees in 0.8 degree steps, normalised to
 * 0..65536 -- there is deliberately no entry for exactly 90 degrees.
 *
 * In the far constants: bank $00 is nearly full and a curve reads this
 * a few dozen times, not a few thousand.
 */
#include "vdi.h"

const UWORD __far vdi_sin_tbl[VDI_SIN_SIZE] = {
        0,   915,  1830,  2744,  3658,  4572,  5484,  6395,
     7305,  8214,  9121, 10026, 10929, 11831, 12729, 13626,
    14519, 15410, 16298, 17183, 18064, 18942, 19816, 20686,
    21553, 22415, 23272, 24125, 24974, 25817, 26656, 27489,
    28317, 29140, 29956, 30767, 31572, 32371, 33163, 33949,
    34729, 35501, 36267, 37026, 37777, 38521, 39258, 39986,
    40708, 41421, 42126, 42823, 43511, 44191, 44862, 45525,
    46179, 46824, 47459, 48086, 48703, 49310, 49908, 50496,
    51075, 51643, 52201, 52750, 53287, 53815, 54332, 54838,
    55334, 55819, 56293, 56756, 57208, 57649, 58078, 58497,
    58903, 59299, 59683, 60055, 60415, 60764, 61101, 61426,
    61739, 62040, 62328, 62605, 62870, 63122, 63362, 63589,
    63804, 64007, 64197, 64375, 64540, 64693, 64833, 64960,
    65075, 65177, 65266, 65343, 65407, 65458, 65496, 65522,
    65534,
};
