#!/usr/bin/env python3
"""Extract EmuTOS's 6x6 system font into gem4xe's strip layout.

WHY A SECOND FACE AT ALL.  The ANTIC device is 320 pixels wide, and with
the 8x8 face that is FORTY columns -- half what every GEM resource is
laid out against, and enough that the desktop's wider dialogs fill the
screen edge to edge with no margin.  A narrower cell buys columns AND
rows: 6x6 gives 53 x 28 where 8x8 gives 40 x 21.

This is Atari's own condensed face, the one the ST uses for icon labels
in low resolution -- which is to say GEM's own answer to a screen that
is short of pixels, rather than one invented here.

THE PACKING IS DIFFERENT from the 8x8's and that is the whole of this
file.  fnt_st_8x8.c is one byte per character per row, 256 of them side
by side.  fnt_st_6x6.c is SIX BITS per character: a row is 192 bytes and
character N's bits start at off_table[N], which for a monospaced face is
N*6.  gem4xe wants one byte per character per row either way -- it is
what makes the device's glyph blit the same code for every face -- so
each glyph is unpacked and left-aligned in its byte, the top six bits
holding it and the bottom two spare.

  python3 tools/fontconv6.py <fnt_st_6x6.c> <out.c>
"""
import re
import sys

SRC_W, SRC_H = 192, 6                   # the donor's form_width, form_height
CELL = 6                                # max_cell_width
OUT_W = 256                             # gem4xe's: one byte per character


def parse(path):
    src = open(path).read()
    m = re.search(r"static const UWORD dat_table\[\d*\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        raise SystemExit(f"{path}: dat_table not found")
    words = [int(w, 16) for w in re.findall(r"0x([0-9a-fA-F]{4})", m.group(1))]
    data = bytearray()
    for w in words:                     # F_STDFORM: high byte first
        data.append((w >> 8) & 0xFF)
        data.append(w & 0xFF)
    want = SRC_W * SRC_H
    if len(data) < want:
        raise SystemExit(f"{path}: {len(data)} bytes, expected {want}")
    return bytes(data[:want])


def unpack(data):
    """One byte per character per row, the six bits left-aligned."""
    out = bytearray(OUT_W * SRC_H)
    for row in range(SRC_H):
        base = row * SRC_W
        for ch in range(OUT_W):
            start = ch * CELL           # monospaced: off_table[N] is N*6
            b = 0
            for i in range(CELL):
                bit = start + i
                if data[base + (bit >> 3)] & (0x80 >> (bit & 7)):
                    b |= 0x80 >> i
            out[row * OUT_W + ch] = b
    return bytes(out)


def emit(data, out):
    with open(out, "w") as f:
        f.write("/* Generated by tools/fontconv6.py -- do not edit.\n"
                " *\n"
                " * The GEM 6x6 system font from EmuTOS (bios/fnt_st_6x6.c),\n"
                " * Copyright (C) 2001-2021 The EmuTOS development team, GPL v2\n"
                " * or later.  Atari's own condensed face -- the one the ST\n"
                " * uses for icon labels in low resolution.\n"
                " *\n"
                " * Repacked into gem4xe's strip: %d bytes per row, %d rows,\n"
                " * character N's byte on row r at r*%d + N, with the six bits\n"
                " * LEFT-ALIGNED in each byte.  The donor packs six bits per\n"
                " * character instead; unpacking here is what lets the device\n"
                " * blit every face with the same code.\n"
                " */\n"
                "#include <stdint.h>\n"
                "#include \"portab.h\"\n\n"
                "const uint8_t FAR font6x6[%d] = {\n" % (OUT_W, SRC_H, OUT_W, len(data)))
        for i in range(0, len(data), 16):
            f.write("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
    print(f"{out}: {len(data)} bytes ({OUT_W}x{SRC_H} strip, 256 glyphs of {CELL} wide)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__.strip().splitlines()[-1])
    emit(unpack(parse(sys.argv[1])), sys.argv[2])
