#!/usr/bin/env python3
"""Extract the GEM 8x8 system font from EmuTOS into a linkable C array.

EmuTOS's bios/fnt_st_8x8.c holds the font as a horizontal STRIP: form_width is
256 bytes and form_height is 8, i.e. one byte per character per scanline, all
256 characters side by side.  Character N's byte on row r is at r*256 + N.
The data is declared as UWORDs in Motorola (big-endian) order, per F_STDFORM.

Emitting 1bpp and expanding to 4bpp on the target -- rather than shipping a
pre-expanded 4bpp blob -- keeps the linked size at 2 KB instead of 8 KB, which
matters because the whole program lives in bank $00.

  python3 tools/fontconv.py <fnt_st_8x8.c> <out.c>
"""
import re
import sys

FORM_W, FORM_H = 256, 8            # bytes per row, rows -- from the Fonthead


def parse(path):
    src = open(path).read()
    m = re.search(r"static const UWORD dat_table\[\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        raise SystemExit(f"{path}: dat_table not found")
    words = [int(w, 16) for w in re.findall(r"0x([0-9a-fA-F]{4})", m.group(1))]
    data = bytearray()
    for w in words:                # F_STDFORM: high byte first
        data.append((w >> 8) & 0xFF)
        data.append(w & 0xFF)
    want = FORM_W * FORM_H
    if len(data) < want:
        raise SystemExit(f"{path}: got {len(data)} bytes, expected {want}")
    return bytes(data[:want])


def emit(data, out):
    with open(out, "w") as f:
        f.write("/* Generated by tools/fontconv.py -- do not edit.\n"
                " *\n"
                " * The GEM 8x8 system font from EmuTOS (bios/fnt_st_8x8.c),\n"
                " * Copyright (C) 2001-2021 The EmuTOS development team, GPL v2\n"
                " * or later.  Stored as a 1bpp strip: %d bytes per row, %d rows,\n"
                " * character N's byte on row r at r*%d + N.\n"
                " *\n"
                " * FAR: the strip is read at start-up, to expand the glyph\n"
                " * masks into VRAM, and by the pixel-by-pixel fallback; it\n"
                " * does not earn 2 KB of bank $00, where every global lives.\n"
                " */\n"
                "#include <stdint.h>\n"
                "#include \"portab.h\"\n\n"
                "const uint8_t FAR font8x8[%d] = {\n" % (FORM_W, FORM_H, FORM_W, len(data)))
        for i in range(0, len(data), 16):
            f.write("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
    print(f"{out}: {len(data)} bytes ({FORM_W}x{FORM_H} strip, 256 glyphs)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__.strip().splitlines()[-1])
    emit(parse(sys.argv[1]), sys.argv[2])
