#!/usr/bin/env python3
"""Does GACS's engine run on the 65816?

GACS -- the GURPS Autoduel Construction Set (~/dev/gacs) -- and RetroWP are
the two applications gem4xe exists for, and both are built the same way: a
portable engine in strict C89 with no I/O, and a shell per platform.  If the
engine compiles for the 65816 and computes the same answers there, the work
left is a shell; if it does not, gem4xe has a problem no amount of AES will
fix.  So this asks, and keeps asking:

  1. every file of engine/src compiles, in BOTH data models -- small (16-bit
     pointers, the model gem4xe's own system uses) and large (24-bit, the
     model an application needs to reach far memory);
  2. the large-data build links with its working set in far RAM;
  3. it RUNS, in Calypsi's own 65816 simulator, against the six tables GACS
     ships -- 27 chassis, 13 engines, 10 tires, 20 weapons -- and computes a
     design without error;
  4. and the footprint is reported, because that is the number that decides
     whether an application fits: bank $00 is 2 KB for an application and
     far memory is 14 MB.

    python3 tools/gacscheck.py [--gacs DIR] [--keep]

Needs the GACS checkout and the Calypsi tool chain; says so and stops
without either.  Not part of `make test`: it depends on another project.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CALYPSI = os.environ.get("CALYPSI", os.path.expanduser("~/dev/toolchains/calypsi-65816"))
GACS = os.environ.get("GACS", os.path.expanduser("~/dev/gacs"))
OUT = os.path.join(ROOT, "build", "gacs")
DRIVER = os.path.join(ROOT, "tools", "gacs", "gacsrun.c")
TABLES = ("CHASSIS.DAT", "ENGINES.DAT", "TIRES.DAT", "SUSPEN.DAT",
          "WEAPONS.DAT", "ACCESS.DAT")
# The linker rules Calypsi ships for a generic large-code/large-data
# machine: RAM in bank $00, code in $01, far data in $03.  Not gem4xe's map
# (src/app/gemapp.scm is), but the same shape, and it needs no target.
SCM = "example/linker-files/linker-large-large-any.scm"


def run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def tables_c(path):
    """GACS's shipped tables as far constants, so the run needs no files."""
    out = ["/* GACS's shipped tables, as far constants.  Generated by",
           " * tools/gacscheck.py -- do not edit. */", "#include <stdint.h>", ""]
    sizes = []
    for i, name in enumerate(TABLES):
        with open(os.path.join(GACS, "data", name), "rb") as f:
            d = f.read()
        sizes.append(len(d))
        out.append(f"/* {name}: {len(d)} bytes */")
        out.append(f"const char __far gacs_tbl{i}[{len(d) + 1}] = {{")
        for k in range(0, len(d), 16):
            out.append("    " + ", ".join(str(b) for b in d[k:k + 16]) + ",")
        out.append("    0 };")
    out.append("const char __far *const gacs_tables[6] = { "
               + ", ".join(f"gacs_tbl{i}" for i in range(6)) + " };")
    out.append("const unsigned gacs_sizes[6] = { "
               + ", ".join(str(n) for n in sizes) + " };")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    return sizes


def sections(mapfile):
    """What the link came to, by section."""
    tot = {}
    for line in open(mapfile):
        m = re.match(r"^(\w+)\s+([0-9a-f]{6})-([0-9a-f]{6})\s+([0-9a-f]{6})\s", line)
        if m:
            tot[m.group(1)] = tot.get(m.group(1), 0) + int(m.group(4), 16)
    return tot


def main(argv):
    keep = "--keep" in argv
    global GACS
    for a in argv:
        if a.startswith("--gacs="):
            GACS = os.path.expanduser(a[7:])
    cc = os.path.join(CALYPSI, "bin", "cc65816")
    ln = os.path.join(CALYPSI, "bin", "ln65816")
    db = os.path.join(CALYPSI, "bin", "db65816")
    for p, what in ((cc, "the Calypsi compiler"), (db, "Calypsi's simulator"),
                    (os.path.join(GACS, "engine", "src"), "GACS's engine")):
        if not os.path.exists(p):
            print(f"gacs-check: no {what} at {p} -- set CALYPSI= or GACS=")
            return 2
    os.makedirs(OUT, exist_ok=True)
    src = sorted(f for f in os.listdir(os.path.join(GACS, "engine", "src"))
                 if f.endswith(".c"))
    inc = os.path.join(GACS, "engine", "include")
    fails = []

    def check(cond, msg):
        if not cond:
            fails.append(msg)
            print(f"  FAIL: {msg}")

    # -- 1. both data models -------------------------------------------------
    for model in ("small", "large"):
        bad = []
        for f in src:
            o = os.path.join(OUT, f"{model}-{f[:-2]}.o")
            r = run([cc, "--code-model=large", f"--data-model={model}", "-O2",
                     "-I", inc, "-o", o, os.path.join(GACS, "engine", "src", f)])
            if r.returncode or r.stderr.strip():
                bad.append((f, r.stderr.strip().splitlines()[0] if r.stderr else "?"))
        print(f"  engine, --data-model={model:<5s} "
              f"{len(src) - len(bad)}/{len(src)} files")
        for f, why in bad:
            print(f"      {f}: {why}")
        check(not bad, f"{len(bad)} of {len(src)} engine files fail at "
                       f"--data-model={model}")

    # -- 2. the tables, and the driver ---------------------------------------
    sizes = tables_c(os.path.join(OUT, "gacsdata.c"))
    print(f"  tables: {', '.join(f'{n}={s}' for n, s in zip(TABLES, sizes))}")
    for name, extra in ((os.path.join(OUT, "gacsdata.c"), []), (DRIVER, ["-I", inc])):
        o = os.path.join(OUT, "large-" + os.path.basename(name)[:-2] + ".o")
        r = run([cc, "--code-model=large", "--data-model=large", "-O2",
                 "-o", o] + extra + [name])
        check(not r.returncode, f"{os.path.basename(name)}: {r.stderr.strip()[:120]}")

    # -- 3. the link, and what it came to ------------------------------------
    objs = [os.path.join(OUT, f) for f in sorted(os.listdir(OUT))
            if f.startswith("large-") and f.endswith(".o")]
    elf = os.path.join(OUT, "gacsrun.elf")
    mp = os.path.join(OUT, "gacsrun.map")
    r = run([ln, "--debug", os.path.join(CALYPSI, SCM)] + objs
            + ["-o", elf, "clib-lc-ld.a", "--semi-hosted",
               "--rtattr", "exit=simplified", "--list-file", mp], cwd=GACS)
    check(not r.returncode and os.path.exists(elf),
          f"the link failed: {(r.stderr or r.stdout).strip()[:200]}")
    if os.path.exists(mp):
        s = sections(mp)
        near = sum(s.get(k, 0) for k in ("code", "data", "zdata", "cdata",
                                         "idata", "data_init_table"))
        far = sum(s.get(k, 0) for k in ("farcode", "far", "zfar", "cfar", "ifar"))
        print(f"  footprint: {s.get('farcode', 0)} bytes of code, "
              f"{s.get('zfar', 0) + s.get('far', 0)} of data and "
              f"{s.get('cfar', 0)} of constants, all far; "
              f"{near} bytes in bank $00")
        check(near < 2048, f"{near} bytes of bank $00 -- an application has 2048")

    # -- 4. run it -----------------------------------------------------------
    if not fails:
        r = run([db, "--exit-breakpoint", "--semi-hosted-root", OUT, elf],
                input="run\nquit\n", timeout=600)
        out = r.stdout
        for line in out.splitlines():
            if line.strip() and not line.startswith(("Calypsi", "(db65816)")):
                print("      " + line.strip())
        check("ad_compute -> 0" in out, "ad_compute did not answer AD_OK")
        check("program exited normally" in out, "the program did not exit normally")
        m = re.search(r"tables: (\d+) chassis, (\d+) engines, (\d+) tires, (\d+) weapons",
                      out)
        check(m and all(int(g) > 0 for g in m.groups()),
              "the tables did not parse into anything")
    if not keep:
        for f in os.listdir(OUT):
            if f.endswith(".o"):
                os.remove(os.path.join(OUT, f))
    print(f"gacs-check: {'PASS' if not fails else 'FAIL'} -- GACS's engine on "
          f"the 65816, {len(fails)} problem(s)")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
