#!/usr/bin/env python3
"""The four far constant blocks src/m31_huge.c reads back.

Generated rather than written out, for the reason build/app_blob.c is:
80,000 bytes of C initialiser is not source anybody reviews, and the RULE
that makes them is what matters.  That rule is in one line here and in one
macro there, and the test is that the program agrees with it.

They have to be CONSTANTS with real values, not zeroed arrays: the point of
this program is a far IMAGE bigger than a bank, and only bytes that are in
the file count towards it.  A zero-initialised array carries none.

    python3 tools/m31data.py build/m31_data.c
"""
import sys

BLK = 20000
NBLK = 3
NPTR = 4000


def fill(b, i):
    return (i * 7 + b * 131 + 5) & 0xFF


def main(out):
    L = ["/* The far constants for src/m31_huge.c.  GENERATED by",
         " * tools/m31data.py -- do not edit.  The rule is fill(b, i) =",
         " * (i * 7 + b * 131 + 5) & 0xFF, and m31_huge.c has it too. */",
         '#include "portab.h"', ""]
    for b in range(NBLK):
        L.append(f"const unsigned char FAR m31_blk{b}[{BLK}] = {{")
        for k in range(0, BLK, 16):
            L.append("    " + ",".join(str(fill(b, i))
                                       for i in range(k, min(k + 16, BLK))) + ",")
        L.append("};")
        L.append("")
    L.append("const unsigned char FAR *const m31_blocks[%d] = { %s };"
             % (NBLK, ", ".join(f"m31_blk{b}" for b in range(NBLK))))
    L.append("")
    # The bulk of the image AND the thing that needs relocating up there.
    # A block of bytes past 64 KB proves the COPY; only an ADDRESS past
    # 64 KB proves the fixup offsets, and a byte array holds none.  So the
    # last constant is an array of four thousand far pointers, each into
    # blk0 at its own index: every one of them is a bank byte the loader
    # has to add to, and enough of them land past $FFFF of image that a
    # u16 offset could not name them.
    L.append(f"const unsigned char FAR *const m31_ptrs[{NPTR}] = {{")
    for k in range(0, NPTR, 8):
        L.append("    " + ",".join(f"m31_blk0+{i}"
                                   for i in range(k, min(k + 8, NPTR))) + ",")
    L.append("};")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
