#!/usr/bin/env python3
"""Extract the GEM VDI fill patterns from EmuTOS into a linkable C file.

EmuTOS's vdi/vdi_fill.c carries the standard tables as UWORD arrays: eight
4-row dithers (DITHER), sixteen 8-row OEM patterns (OEMPAT), six 8-row coarse
hatches (HATCH0) and six 16-row fine hatches (HATCH1).  Bit 15 of a row is the
leftmost pixel of a 16-aligned screen word.

The output is checked in (src/vdi/fillpat.c) so the host reference reads the
same words the target links; tests/host/test_fillpat.py re-parses the donor
and fails if the two ever differ.

  python3 tools/patconv.py <vdi_fill.c> <out.c>
"""
import re
import sys

# donor name, our name, rows per pattern, pattern count
TABLES = (
    ("DITHER", "fill_dither", 4, 8),
    ("OEMPAT", "fill_oem",    8, 16),
    ("HATCH0", "fill_hatch0", 8, 6),
    ("HATCH1", "fill_hatch1", 16, 6),
)


def parse(path):
    src = open(path).read()
    out = {}
    for donor, ours, rows, count in TABLES:
        m = re.search(r"const UWORD %s\[(\d+)\]\s*=\s*\{(.*?)\};" % donor, src, re.S)
        if not m:
            raise SystemExit(f"{path}: {donor} not found")
        body = re.sub(r"/\*.*?\*/", "", m.group(2), flags=re.S)
        words = [int(w, 16) for w in re.findall(r"0x([0-9a-fA-F]{1,4})", body)]
        want = rows * count
        if int(m.group(1)) != want or len(words) != want:
            raise SystemExit(f"{path}: {donor} has {len(words)} words, expected {want}")
        out[ours] = words
    return out


def emit(tables, out):
    with open(out, "w") as f:
        f.write("/* Generated by tools/patconv.py -- do not edit.\n"
                " *\n"
                " * The GEM VDI fill patterns from EmuTOS (vdi/vdi_fill.c),\n"
                " * Copyright (C) 2002-2022 The EmuTOS development team, GPL v2\n"
                " * or later.  One UWORD per row, bit 15 the leftmost pixel of a\n"
                " * 16-aligned screen word; a pattern's rows are indexed by y AND\n"
                " * its row mask (rows - 1).\n"
                " */\n"
                "#include \"vdi.h\"\n\n")
        for donor, ours, rows, count in TABLES:
            words = tables[ours]
            f.write(f"/* {donor}: {count} patterns of {rows} rows */\n")
            f.write(f"const UWORD {ours}[{rows * count}] = {{\n")
            for i in range(0, len(words), rows):
                chunk = words[i:i + rows]
                for j in range(0, len(chunk), 8):
                    f.write("    " + ", ".join(f"0x{w:04X}" for w in chunk[j:j + 8])
                            + ",\n")
            f.write("};\n\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    emit(parse(sys.argv[1]), sys.argv[2])
