#!/usr/bin/env python3
"""Extract the VDI's sine table from EmuTOS into a gem4xe C file.

The GDPs (circles, arcs, pie slices, rounded boxes) need sines of 0 to
89.6 degrees in 0.8 degree steps, normalised to 0..65536.  EmuTOS's
vdi/vdi_gdp.c holds them as sin_tbl[]; they are NOT round(sin(x)*65536)
-- the table came from DRI and differs in the last digits -- so they are
copied rather than recomputed, and read back out of the generated file
by tools/vdiref.py so the reference cannot drift from the driver.

  python3 tools/sinconv.py <emutos>/vdi/vdi_gdp.c src/vdi/sintbl.c
"""
import re
import sys

SIZE = 113          # (MAX_TABLE_ANGLE / 8) + 1, with MAX_TABLE_ANGLE 896

HEAD = """/* Generated by tools/sinconv.py -- do not edit.
 *
 * The VDI's sine table from EmuTOS (vdi/vdi_gdp.c),
 * Copyright 1982 by Digital Research Inc., Copyright 1999 by Caldera,
 * Inc., Copyright 2002-2022 The EmuTOS development team, GPL v2 or
 * later.  Sines of 0 to 89.6 degrees in 0.8 degree steps, normalised to
 * 0..65536 -- there is deliberately no entry for exactly 90 degrees.
 *
 * In the far constants: bank $00 is nearly full and a curve reads this
 * a few dozen times, not a few thousand.
 */
#include "portab.h"
#include "vdi.h"

const UWORD FAR vdi_sin_tbl[VDI_SIN_SIZE] = {
"""


def parse(src):
    text = open(src).read()
    m = re.search(r"sin_tbl\[SINE_TABLE_SIZE\]\s*=\s*\{(.*?)\}", text, re.S)
    if not m:
        raise SystemExit(f"{src}: no sin_tbl[] found")
    vals = [int(v) for v in re.findall(r"\d+", m.group(1))]
    if len(vals) != SIZE:
        raise SystemExit(f"{src}: {len(vals)} entries, expected {SIZE}")
    return vals


def main(args):
    vals = parse(args[0])
    with open(args[1], "w") as f:
        f.write(HEAD)
        for i in range(0, SIZE, 8):
            f.write("    " + ", ".join(f"{v:5d}" for v in vals[i:i + 8]) + ",\n")
        f.write("};\n")
    print(f"{args[1]}: {SIZE} entries")


if __name__ == "__main__":
    main(sys.argv[1:])
